### ISSUE TITLE
Unable to start - pydantic.errors.ConfigError

### ISSUE THREAD

**Issue by ioma8** [OpenInterpreter/open-interpreter#1100]
### Describe the bug

When I want to start with command `interpreter` I only get the following erorr message in console:
```
Traceback (most recent call last):
  File "/Users/myuser/opt/anaconda3/bin/interpreter", line 5, in <module>
    from interpreter.terminal_interface.start_terminal_interface import main
  File "/Users/myuser/opt/anaconda3/lib/python3.9/site-packages/interpreter/__init__.py", line 2, in <module>
    from .core.core import OpenInterpreter
  File "/Users/myuser/opt/anaconda3/lib/python3.9/site-packages/interpreter/core/core.py", line 17, in <module>
    from .llm.llm import Llm
  File "/Users/myuser/opt/anaconda3/lib/python3.9/site-packages/interpreter/core/llm/llm.py", line 1, in <module>
    import litellm
  File "/Users/myuser/opt/anaconda3/lib/python3.9/site-packages/litellm/__init__.py", line 6, in <module>
    from litellm.proxy._types import KeyManagementSystem, KeyManagementSettings
  File "/Users/myuser/opt/anaconda3/lib/python3.9/site-packages/litellm/proxy/_types.py", line 81, in <module>
    class ModelInfo(LiteLLMBase):
  File "/Users/myuser/opt/anaconda3/lib/python3.9/site-packages/litellm/proxy/_types.py", line 106, in ModelInfo
    def set_model_info(cls, values):
  File "pydantic/class_validators.py", line 134, in pydantic.class_validators.root_validator.dec
  File "pydantic/class_validators.py", line 152, in pydantic.class_validators._prepare_validator
pydantic.errors.ConfigError: duplicate validator function "litellm.proxy._types.ModelInfo.set_model_info"; if this is intended, set `allow_reuse=True`
```

### Reproduce

1. Install interpreter via PIP:
`pip install open-interpreter`

2. Run it from commandline: `interpreter` or `interpreter --model gpt-3.5-turbo`
3. Get the error 

### Expected behavior

Should start interpreter 

### Open Interpreter version

pip show open-interpreter gives error

### Python version

3.9.12

### Operating System name and version

macOs 14.2.1 (M1)

**Comment by Notnaton** [comment]
Update python to 3.10 or 3.11.
Check pydantic version:
`pip show pydantic `

**Comment by MikeBirdTech** [comment]
@ioma8 Did this resolve your issue?

**Comment by Notnaton** [comment]
Closing, no reply
