### ISSUE TITLE
OI freezes then gives Jupyter error

### ISSUE THREAD

**Issue by cfortune** [OpenInterpreter/open-interpreter#1129]
### Describe the bug

I tried to get OI to update my instance of gpt-pilot.  It froze for > 10 minutes, so I hit Ctrl-c (keyboard interrupt) and it gave a weird error about Jupyter.

PS C:\projects> interpreter -y --multi_line
> how do I update gpt-pilot?

  The instructions for updating GPT-Pilot might slightly vary depending on the configuration of your system. Here's a generalized
  plan:
   1 Check the current version of GPT-Pilot installed.
   2 Search for the latest version of GPT-Pilot online.
   3 If the latest version is different from the installed version, proceed with the update.
   4 Update GPT-Pilot.

  Let's start with step 1: Checking the current version of GPT-Pilot.

  import gpt_pilot  .**... IT FREEZES HERE.  THIS IS ACTUALLY A FOOL'S ERRAND, SINCE IT'S NOT AN EXECUTABLE PROGRAM, BUT A GIT REPO.  IT SHOULD TIME OUT AND ADMIT FAILURE AND ASK FOR FEEDBACK**

  # Get the current version.
  gpt_pilot.__version__

  Traceback (most recent call last):
    File "C:\bin\miniconda3\Lib\site-packages\interpreter\core\computer\terminal\languages\jupyter_language.py", line 97, in run
      yield from self._capture_output(message_queue)
    File "C:\bin\miniconda3\Lib\site-packages\interpreter\core\computer\terminal\languages\jupyter_language.py", line 229, in
  _capture_output
      output = message_queue.get(timeout=0.1)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\bin\miniconda3\Lib\queue.py", line 180, in get
      self.not_empty.wait(remaining)
    File "C:\bin\miniconda3\Lib\threading.py", line 324, in wait
      gotit = waiter.acquire(True, timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  KeyboardInterrupt  **... THIS WAS MY CTRL-C**

Bad address (C:\projects\libzmq\src\fq.cpp:87)            **... THIS IS THE WRONG FOLDER.  I'M UNABLE TO FIND THIS PROGRAM ON MY PC**
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
PS C:\projects> [IPKernelApp] WARNING | Parent appears to have exited, shutting down.

### Reproduce

PS C:\projects> interpreter -y --multi_line
> how do I update gpt-pilot?

### Expected behavior

it searches the web and finds the answer then prints it.  and doesn't freeze or crash

### Open Interpreter version

Open Interpreter 0.2.4 New Computer Update

### Python version

3.11.5

### Operating System name and version

Windows 10

**Comment by MikeBirdTech** [comment]
Hi @cfortune 
Does the same error occur without the `--multi_line` flag?

**Comment by cfortune** [comment]
the source of the error was an empty file in the skills dir.  Deleting the file caused everything to begin working again.  
`AppData\Local\open-interpreter\open-interpreter\skills`

recommended fix: main prog should check for the viability of `skills` scripts at start time, and emit an error, instead:

**Comment by interpreterwork** [comment]
Thank you for reporting this and for helping build the classic Python version of Open Interpreter. This issue concerns the earlier Python/LiteLLM/Jupyter product; this repository now tracks the Rust Open Interpreter built on Codex. We are closing the legacy report here so current product tracking starts clean. If you still want to pursue it, the community-maintained classic fork is https://github.com/endolith/open-interpreter. If the same problem affects the current Interpreter release, please open a new issue with the current template and include the version, provider, model, wire API, harness, platform, and reproduction.
