### ISSUE TITLE
pip --upgrade didn't work, turned working open-interpreter package into non-working package (possible fixes inside)

### ISSUE THREAD

**Issue by AncalagonX** [OpenInterpreter/open-interpreter#1134]
### Describe the bug

On Windows, I had a working installation of open-interpreter 0.2.2 or 0.2.3 on Python 3.11. Earlier this week, I decided to close my long-running interpreter.exe session, and run a `pip install open-interpreter --upgrade` (without `--force-reinstall`).

It did a normal pip upgrade of open-interpreter to 0.2.4, and I tried to run it using the command `interpreter.exe` (it's in my system variables).

Unfortunately, it didn't run, and instead gave me this error: 

```PS C:\Important_Stuff> interpreter.exe
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\fflag\AppData\Roaming\Python\Python311\Scripts\interpreter.exe\__main__.py", line 4, in <module>
  File "C:\Users\fflag\AppData\Roaming\Python\Python311\site-packages\interpreter\__init__.py", line 2, in <module>
    from .core.core import OpenInterpreter
  File "C:\Users\fflag\AppData\Roaming\Python\Python311\site-packages\interpreter\core\core.py", line 15, in <module>
    from .computer.computer import Computer
  File "C:\Users\fflag\AppData\Roaming\Python\Python311\site-packages\interpreter\core\computer\computer.py", line 8, in <module>
    from .display.display import Display
  File "C:\Users\fflag\AppData\Roaming\Python\Python311\site-packages\interpreter\core\computer\display\display.py", line 23, in <module>
    from ..utils.computer_vision import find_text_in_image, pytesseract_get_text
  File "C:\Users\fflag\AppData\Roaming\Python\Python311\site-packages\interpreter\core\computer\utils\computer_vision.py", line 7, in <module>
    cv2 = lazy_import("cv2")
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\fflag\AppData\Roaming\Python\Python311\site-packages\interpreter\core\utils\lazy_import.py", line 19, in lazy_import
    loader = importlib.util.LazyLoader(spec.loader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib.util>", line 284, in __init__
  File "<frozen importlib.util>", line 275, in __check_eager_loader
TypeError: loader must define exec_module()
```

I tried downgrading to 0.2.3, but it gave me the same error as above. I tried upgrading/reinstalling frozenlist since I saw it mentioned above, no dice.

**I finally was able to solve it when I ran `pip install --upgrade open-interpreter opencv-python pytesseract`, which was every package I could find mentioned there.**

### Reproduce

Steps are above in the description

### Expected behavior

Running `pip install open-interpreter --upgrade` should work.

### Open Interpreter version

0.2.4

### Python version

3.11.8

### Operating System name and version

Windows 11

**Comment by interpreterwork** [comment]
Thank you for reporting this and for helping build the classic Python version of Open Interpreter. This issue concerns the earlier Python/LiteLLM/Jupyter product; this repository now tracks the Rust Open Interpreter built on Codex. We are closing the legacy report here so current product tracking starts clean. If you still want to pursue it, the community-maintained classic fork is https://github.com/endolith/open-interpreter. If the same problem affects the current Interpreter release, please open a new issue with the current template and include the version, provider, model, wire API, harness, platform, and reproduction.
