### ISSUE TITLE
No module named 'openai.types.beta.threads.message_content'

### ISSUE THREAD

**Issue by nanowell** [OpenInterpreter/open-interpreter#1284]
### Describe the bug

PS C:\Users\user> interpreter
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Scripts\interpreter.exe\__main__.py", line 4, in <module>
    from interpreter.terminal_interface.start_terminal_interface import main
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\__init__.py", line 2, in <module>
    from .core.core import OpenInterpreter
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\core.py", line 17, in <module>
    from .llm.llm import Llm
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\llm\llm.py", line 1, in <module>
    import litellm
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\__init__.py", line 764, in <module>
    from .llms.openai import OpenAIConfig, OpenAITextCompletionConfig, MistralConfig
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\llms\openai.py", line 28, in <module>
    from ..types.llms.openai import *
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\types\llms\openai.py", line 12, in <module>
    from openai.types.beta.threads.message_content import MessageContent
ModuleNotFoundError: No module named 'openai.types.beta.threads.message_content'

### Reproduce

PS C:\Users\user> iex "& {$(irm https://raw.githubusercontent.com/KillianLucas/open-interpreter/main/installers/oi-windows-installer.ps1)}"
PS C:\Users\user> interpreter
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Scripts\interpreter.exe\__main__.py", line 4, in <module>
    from interpreter.terminal_interface.start_terminal_interface import main
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\__init__.py", line 2, in <module>
    from .core.core import OpenInterpreter
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\core.py", line 17, in <module>
    from .llm.llm import Llm
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\llm\llm.py", line 1, in <module>
    import litellm
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\__init__.py", line 764, in <module>
    from .llms.openai import OpenAIConfig, OpenAITextCompletionConfig, MistralConfig
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\llms\openai.py", line 28, in <module>
    from ..types.llms.openai import *
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\types\llms\openai.py", line 12, in <module>
    from openai.types.beta.threads.message_content import MessageContent
ModuleNotFoundError: No module named 'openai.types.beta.threads.message_content'

### Expected behavior

Launching app successfully after installation.

### Open Interpreter version

0.2.5

### Python version

3.10

### Operating System name and version

Windows 10

**Comment by miketam** [comment]
check your litellm version. my version: 1.10.2 is OK
