### ISSUE TITLE
`interpreter.computer.keyboard.write` method fails when run by a macOS background service

### ISSUE THREAD

**Issue by getvictor** [OpenInterpreter/open-interpreter#1292]
### Describe the bug

I have a background macOS service ([fleetd](https://fleetdm.com/docs/get-started/anatomy#fleetd)) that's trying to run a script using interpreter APIs.

It fails `keyboard.write` because it doesn't seem to have access to [NSPasteboard.generalPasteboard](https://developer.apple.com/documentation/appkit/nspasteboard/1530091-generalpasteboard?language=objc)

I'm not sure why it can't get a handle to the generalPasteboard. The service has System Events TCC permissions and all other requests for TCC permissions that popped up (Accessibility, Recording Screen and Audio).

Looking at the error, the method should work even without access to the generalPasteboard. interpreter should write one character at a time instead of trying to copy/paste.

```
Traceback (most recent call last):
  File "/Users/victor/work/migrate-to-fleet/main.py", line 44, in <module>
    interpreter.computer.keyboard.write("Profiles")
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/computer/keyboard/keyboard.py", line 40, in write
    self.computer.clipboard.copy(line)
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/computer/clipboard/clipboard.py", line 27, in copy
    pyperclip.copy(text)
  File "/opt/homebrew/lib/python3.11/site-packages/pyperclip/__init__.py", line 139, in copy_osx_pyobjc
    board.declareTypes_owner_([AppKit.NSStringPboardType], None)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'declareTypes_owner_'
```

### Reproduce

1. [Set up Fleet server](https://github.com/fleetdm/fleet/blob/main/docs/Get%20started/tutorials-and-guides.md) and install a Fleet agent on your macOS device.
2. [Execute a script](https://fleetdm.com/docs/using-fleet/scripts#execute-a-script) via your Fleet agent. The script can be like:
```sh
#!/bin/sh
/Users/<myUsername>/myPythonScript.py
```
The python script should try and use `interpreter.computer.keyboard.write("Profiles")`

### Expected behavior

I expected `interpreter.computer.keyboard.write("Profiles")` to work.

### Open Interpreter version

0.2.5

### Python version

3.11.9

### Operating System name and version

macOS 14

### Additional context

I'm trying to create a demo where I use an Open Interpreter script to remediate an IT policy failure.

**Comment by KillianLucas** [comment]
Hey @getvictor! Thanks for discovering this. Were you able to find a way around it? Does pyautogui work in this environment, or another library like pynput? Would be happy to swap out the keyboard controlling library to make it work with fleet.

**Comment by getvictor** [comment]
> Hey @getvictor! Thanks for discovering this and making such an incredible demo!
> 
> Were you able to find a way around this? Does pyautogui work in this environment, or another library like pynput? Would be happy to swap out the keyboard controlling library to make it work with fleet.

I ended up writing 1 character at a time as a workaround. It was definitely slower.

**Comment by m13v** [comment]
this is a macOS TCC permission issue. background services don't get the same accessibility/input permissions as foreground apps. we hit this exact thing building a desktop automation agent - the fix is to use CGEvent APIs instead of NSPasteboard for keyboard input, and make sure the process (or its parent app bundle) has explicit Accessibility permission in System Settings. launchd services need special entitlements for this.

**Comment by m13v** [comment]
our macOS automation that handles these TCC permission issues: https://github.com/mediar-ai/mcp-server-macos-use/blob/main/Sources/MCPServer/main.swift - uses CGEvent and AXUIElement APIs with proper accessibility permissions.

**Comment by interpreterwork** [comment]
Thank you for reporting this and for helping build the classic Python version of Open Interpreter. This issue concerns the earlier Python/LiteLLM/Jupyter product; this repository now tracks the Rust Open Interpreter built on Codex. We are closing the legacy report here so current product tracking starts clean. If you still want to pursue it, the community-maintained classic fork is https://github.com/endolith/open-interpreter. If the same problem affects the current Interpreter release, please open a new issue with the current template and include the version, provider, model, wire API, harness, platform, and reproduction.
