### ISSUE TITLE
interpreter.exe fails to start on 0.3.0

### ISSUE THREAD

**Issue by AncalagonX** [OpenInterpreter/open-interpreter#1310]
CONGRATS on the big 0.3.0 release! Sorry to throw this up at you right away, but I got a show-stopper:

### Describe the bug

interpreter.exe fails to start on 0.3.0 after using `pip install --upgrade open-interpreter`:

# TEMPORARY EASY FIX:

1. Just run this command:
```
pip install git+https://github.com/OpenInterpreter/open-interpreter.git@main
```
2. **That's it, you're done!** interpreter.exe works now. You can also use this to install commits before they make it into releases.
3. Oh, looks like @KillianLucas released a bug fix release while I was adding this workaround. **You guys rock!** Thanks for all your hard work on this stellar piece of software.

-------------------

**Continuing the original bug report below:**

```
PS C:\+++Important\video_transcription01a> interpreter.exe
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\generic_folder\AppData\Roaming\Python\Python311\Scripts\interpreter.exe\__main__.py", line 4, in <module>
  File "C:\Users\generic_folder\AppData\Roaming\Python\Python311\site-packages\interpreter\__init__.py", line 4, in <module>
    interpreter = OpenInterpreter()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\generic_folder\AppData\Roaming\Python\Python311\site-packages\interpreter\core\core.py", line 122, in __init__
    self.computer = Computer(self) if computer is None else computer
                    ^^^^^^^^^^^^^^
  File "C:\Users\generic_folder\AppData\Roaming\Python\Python311\site-packages\interpreter\core\computer\computer.py", line 36, in __init__
    self.sms = SMS(self)
               ^^^^^^^^^
  File "C:\Users\generic_folder\AppData\Roaming\Python\Python311\site-packages\interpreter\core\computer\sms\sms.py", line 12, in __init__
    self.database_path = self.resolve_database_path()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\generic_folder\AppData\Roaming\Python\Python311\site-packages\interpreter\core\computer\sms\sms.py", line 15, in resolve_database_path
    if os.geteuid() == 0:  # Running as root
       ^^^^^^^^^^
AttributeError: module 'os' has no attribute 'geteuid'. Did you mean: 'getpid'?
```

### Reproduce

I am on Windows 10, and the previous interpreter 0.2.6 worked fine.

### Expected behavior

It should run.

### Open Interpreter version

0.3.0

### Python version

3.11.9

### Operating System name and version

Windows 10

**Comment by alfredwallace7** [comment]
Same here on Windows 11 Python 3.11.4

**Comment by filip-van-hoeckel** [comment]
+1

**Comment by pooxid** [comment]
+1

**Comment by greenmojo2** [comment]
+1

**Comment by AncalagonX** [comment]
Fixed, thanks!
