### ISSUE TITLE
 "Object of type PhiConfig is not JSON serializable" error on --vision parameter

### ISSUE THREAD

**Issue by Swallow74** [OpenInterpreter/open-interpreter#1312]
### Describe the bug

When I use --vision parameter on mac m1 I receive this error: 
Loading Moondream (vision)...

Traceback (most recent call last):
  File "/Users/macbookair/anaconda3/bin/interpreter", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/interpreter/terminal_interface/start_terminal_interface.py", line 520, in main
    start_terminal_interface(interpreter)
  File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/interpreter/terminal_interface/start_terminal_interface.py", line 379, in start_terminal_interface
    interpreter.computer.vision.load()
  File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/interpreter/core/computer/vision/vision.py", line 42, in load
    self.model = transformers.AutoModelForCausalLM.from_pretrained(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 444, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 938, in from_pretrained
    return config_class.from_pretrained(pretrained_model_name_or_path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/transformers/configuration_utils.py", line 554, in from_pretrained
    return cls.from_dict(config_dict, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/transformers/configuration_utils.py", line 725, in from_dict
    logger.info(f"Model config {config}")
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/transformers/configuration_utils.py", line 757, in __repr__
    return f"{self.__class__.__name__} {self.to_json_string()}"
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookair/anaconda3/lib/python3.11/site-packages/transformers/configuration_utils.py", line 836, in to_json_string
    return json.dumps(config_dict, indent=2, sort_keys=True) + "\n"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbookair/anaconda3/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/Users/macbookair/anaconda3/lib/python3.11/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/Users/macbookair/anaconda3/lib/python3.11/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Users/macbookair/anaconda3/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/Users/macbookair/anaconda3/lib/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/Users/macbookair/anaconda3/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PhiConfig is not JSON serializable

### Reproduce

 ❯ interpreter --local --vision

### Expected behavior

Successful loading of the vision model

### Open Interpreter version

0.3.1

### Python version

3.11

### Operating System name and version

MacOS 14.5

**Comment by Translucent504** [comment]
abay ullu ka patha how did u solve it

**Comment by lathinharoon** [comment]
hi, i am also encountering the same problem. Did you manage to find whats causing the issue?
