### ISSUE TITLE
NameError: name 'interpreter' is not defined after installation

### ISSUE THREAD

**Issue by littleblack111** [OpenInterpreter/open-interpreter#1432]
### Describe the bug

After installing on arch, with pip install(python3.12). it gave that error:
```
Traceback (most recent call last):
  File "/home/system/.local/bin/interpreter", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/system/.local/lib/python3.12/site-packages/interpreter/terminal_interface/start_terminal_interface.py", line 610, in main
    start_terminal_interface(interpreter)
  File "/home/system/.local/lib/python3.12/site-packages/interpreter/terminal_interface/start_terminal_interface.py", line 558, in start_terminal_interface
    validate_llm_settings(
  File "/home/system/.local/lib/python3.12/site-packages/interpreter/terminal_interface/validate_llm_settings.py", line 48, in validate_llm_settings
    display_welcome_message_once()
  File "/home/system/.local/lib/python3.12/site-packages/interpreter/terminal_interface/validate_llm_settings.py", line 120, in display_welcome_message_once
    interpreter.display_message(
    ^^^^^^^^^^^
NameError: name 'interpreter' is not defined
```

### Reproduce

1. pip install open-interpreter
2. run `interpreter`
3. the error occurs

### Expected behavior

just runs without any errors

### Open Interpreter version

0.3.9

### Python version

3.12.5

### Operating System name and version

Arch Linux Rolling

**Comment by littleblack111** [comment]
Tried the installation script. does the same thing

**Comment by fatherfox** [comment]
I got the same error. But it works ok on local mode.

**Comment by beagenio** [comment]
Same issue after installation by pip or by link : iex "& {$(irm https://raw.githubusercontent.com/KillianLucas/open-interpreter/main/installers/oi-windows-installer-conda.ps1)}"
Error message is that "interpreter"  isn't recognized as internal or external command 
PS D:\INTERPRETER\open-interpreter-main> interpreter
interpreter : Le terme «interpreter» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou
programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès
est correct et réessayez.
Au caractère Ligne:1 : 1
+ interpreter
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (interpreter:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by bharat555** [comment]
seems to be a bug in 0.3.9, works with

```
pip uninstall open-interpreter
pip install open-interpreter==0.3.8
```

**Comment by Notnaton** [comment]
0.3.9 is not out yet... Latest release is 0.3.8

**Comment by littleblack111** [comment]
> seems to be a bug in 0.3.9, works with
> 
> ```
> pip uninstall open-interpreter
> pip install open-interpreter==0.3.8
> ```

ty! that worked

**Comment by beagenio** [comment]
Done but bug is still in
The version 0.3.9 has been uninstalled and 0.3.8 installed
Launching Open Interpreter
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\botin\miniconda3\envs\oi\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\botin\miniconda3\envs\oi\Lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 610, in main
    start_terminal_interface(interpreter)
  File "C:\Users\botin\miniconda3\envs\oi\Lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 558, in start_terminal_interface
    validate_llm_settings(
  File "C:\Users\botin\miniconda3\envs\oi\Lib\site-packages\interpreter\terminal_interface\validate_llm_settings.py", line 48, in validate_llm_settings
    display_welcome_message_once()
  File "C:\Users\botin\miniconda3\envs\oi\Lib\site-packages\interpreter\terminal_interface\validate_llm_settings.py", line 120, in display_welcome_message_once
    interpreter.display_message(
    ^^^^^^^^^^^
NameError: name 'interpreter' is not defined

**Comment by beagenio** [comment]
Some information may works 
 WARNING: The scripts i.exe, interpreter.exe and wtf.exe are installed in 'C:\Users\botin\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.

**Comment by Notnaton** [comment]
Make sure to add python/scripts to PATH

**Comment by michaelzdrav** [comment]
> seems to be a bug in 0.3.9, works with
> 
> ```
> pip uninstall open-interpreter
> pip install open-interpreter==0.3.8
> ```

This is probably the best fix for now until it is resolved.

**Comment by dorianherle** [comment]
Same issue for me

**Comment by littleblack111** [comment]
solved by @bharat555 's temp solution:
```
pip uninstall open-interpreter
pip install open-interpreter==0.3.8
```

**Comment by KillianLucas** [comment]
Fixed! Sorry about this ya'll. Broke if you ran it for the first time without an OpenAI key, because we started using `interpreter.display_message` inside the welcome message — before interpreter was defined. (Worked fine for testers because we had OpenAI keys.) Will push to `pip` in around an hour. 👍

**Comment by KillianLucas** [comment]
And many thanks @littleblack111 for opening this issue and @Notnaton and @bharat555 for investigating and recommending a fix.

**Comment by Kreijstal** [comment]
how long till pipy updates?

**Comment by KillianLucas** [comment]
@Kreijstal it's up! :) 0.3.10 on `pip`.
