### ISSUE TITLE
problem running with ollama

### ISSUE THREAD

**Issue by williamlee1982** [OpenInterpreter/open-interpreter#1441]
### Describe the bug

get the following error

`Loading llama3.1...

Traceback (most recent call last):
  File "/opt/homebrew/bin/interpreter", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/terminal_interface/start_terminal_interface.py", line 610, in main
    start_terminal_interface(interpreter)
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/terminal_interface/start_terminal_interface.py", line 473, in start_terminal_interface
    interpreter = profile(
                  ^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/terminal_interface/profiles/profiles.py", line 64, in profile
    return apply_profile(interpreter, profile, profile_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/terminal_interface/profiles/profiles.py", line 148, in apply_profile
    exec(profile["start_script"], scope, scope)
  File "<string>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/core.py", line 145, in local_setup
    self = local_setup(self)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/terminal_interface/local_setup.py", line 314, in local_setup
    interpreter.computer.ai.chat("ping")
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/computer/ai/ai.py", line 134, in chat
    for chunk in self.computer.interpreter.llm.run(messages):
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/llm/llm.py", line 86, in run
    self.load()
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/llm/llm.py", line 397, in load
    self.interpreter.computer.ai.chat("ping")
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/computer/ai/ai.py", line 134, in chat
    for chunk in self.computer.interpreter.llm.run(messages):
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/llm/llm.py", line 324, in run
    yield from run_text_llm(self, params)
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/llm/run_text_llm.py", line 20, in run_text_llm
    for chunk in llm.completions(**params):
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/llm/llm.py", line 466, in fixed_litellm_completions
    raise first_error  # If all attempts fail, raise the first error
    ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/llm/llm.py", line 443, in fixed_litellm_completions
    yield from litellm.completion(**params)
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/llms/ollama.py", line 371, in ollama_completion_stream
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/llms/ollama.py", line 329, in ollama_completion_stream
    raise OllamaError(
litellm.llms.ollama.OllamaError: b''`

### Reproduce

1. interpreter --local
2. select Ollama
3. select llama3.1

### Expected behavior

work

### Open Interpreter version

0.3.12

### Python version

Python 3.12.5

### Operating System name and version

masOS 14.6.1

**Comment by everiori** [comment]
same problem here, and I can run interpreter on a ubuntu server and connect to remote ollama, but get the ollam error when running interpreter on my mac

**Comment by MikeBirdTech** [comment]
Make sure you are using python 3.10 or 3.11. the latest oi, and latest ollama

**Comment by duchu** [comment]
I have latest ollama and python 3.12
