### ISSUE TITLE
Remote ollama/llava (localhost:11434) fails to load in OS mode

### ISSUE THREAD

**Issue by Grantham00** [OpenInterpreter/open-interpreter#1486]
### Describe the bug

Attempting to run ollama/llava in OS mode gives the following error:
I'm not sure if it has to do with this specific model or not, or if being pointed to a remote ollama server is the issue.

```
PS C:\Users\grant> interpreter --model ollama/llava --api_base http://localhost:11434 --os

▌ OS Control enabled

Warning: In this mode, Open Interpreter will not require approval before performing actions. Be ready to close your
terminal.

Loading llava...

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\grant\AppData\Local\Programs\Python\Python312\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\grant\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 611, in main
    start_terminal_interface(interpreter)
  File "C:\Users\grant\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 559, in start_terminal_interface
    validate_llm_settings(
  File "C:\Users\grant\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\terminal_interface\validate_llm_settings.py", line 109, in validate_llm_settings
    interpreter.llm.load()
  File "C:\Users\grant\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\core\llm\llm.py", line 397, in load
    self.interpreter.computer.ai.chat("ping")
  File "C:\Users\grant\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\core\computer\ai\ai.py", line 134, in chat
    for chunk in self.computer.interpreter.llm.run(messages):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\grant\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\core\llm\llm.py", line 322, in run
    yield from run_tool_calling_llm(self, params)
  File "C:\Users\grant\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\core\llm\run_tool_calling_llm.py", line 178, in run_tool_calling_llm
    for chunk in llm.completions(**request_params):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\grant\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\core\llm\llm.py", line 466, in fixed_litellm_completions
    raise first_error  # If all attempts fail, raise the first error
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\grant\AppData\Local\Programs\Python\Python312\Lib\site-packages\interpreter\core\llm\llm.py", line 443, in fixed_litellm_completions
    yield from litellm.completion(**params)
  File "C:\Users\grant\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\llms\ollama.py", line 376, in ollama_completion_stream
    raise e
  File "C:\Users\grant\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\llms\ollama.py", line 352, in ollama_completion_stream
    response_content = "".join(content_chunks)
                       ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 1: expected str instance, NoneType found
```

### Reproduce

1. Start ollama (mine is in docker @ localhost:11434) 
(`docker run -d -p 3000:8080 --gpus all -e OLLAMA_BASE_URL=http://localhost:11434 -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main`) and download llava
2. Launch open-interpreter with
`interpreter --model ollama/llava --api_base http://localhost:11434 --os`

### Expected behavior

Expected to successfully load the model and launch interpreter in OS mode.

### Screenshots

![image](https://github.com/user-attachments/assets/2ade1d66-ec81-45a3-99b0-7c49eb76999c)

### Open Interpreter version

0.3.14

### Python version

3.12.7

### Operating System name and version

Windows 11

### Additional context

I followed the Ollama Getting Started guide, my Ollama install is the default docker run w/ CUDA. 
`docker run -d -p 3000:8080 --gpus all -e OLLAMA_BASE_URL=http://localhost:11434 -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main`

I'm also running OpenWebUI separately (not the OpenWebUI/Ollama bundled docker image).

I am noob, please let me know if I can provide any additional info. Thanks!

**Comment by MikeBirdTech** [comment]
For the time being, os mode will be using Claude computer use. We're working on a way to restructure this
