### ISSUE TITLE
Fails with "json.decoder.JSONDecodeError" trying to manipulate with screen using Antropic

### ISSUE THREAD

**Issue by artemu78** [OpenInterpreter/open-interpreter#1507]
### Describe the bug

I've run "interpreter --os" to play with anthropic OS control feature and it crashed with "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"

### Reproduce

I've run "interpreter --os", set a key and asked if it can hear me through the mic

it tried to open settings and failed:

I'll click on the Sound settings to check your microphone settings.

{"action": "mouse_move", "coordinate": [40, 369]}{"action": "left_click"}{"action": "screenshot"}

I notice I'm still in the Notifications settings. Let me try clicking the Sound icon again to access sound settings.

{"action": "key", "text": "Command+Space"}{"action": "type", "text": "Sound"}

Let me click the "Open" button to access Sound settings.

{"action": "mouse_move", "coordinate": [558, 202]}Traceback (most recent call last):
  File "/opt/anaconda3/bin/interpreter", line 5, in <module>
    from interpreter.terminal_interface.start_terminal_interface import main
  File "/opt/anaconda3/lib/python3.12/site-packages/interpreter/__init__.py", line 54, in <module>
    run_async_main()
  File "/opt/anaconda3/lib/python3.12/site-packages/interpreter/computer_use/loop.py", line 528, in run_async_main
    asyncio.run(main())
  File "/opt/anaconda3/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/interpreter/computer_use/loop.py", line 505, in main
    async for chunk in sampling_loop(
  File "/opt/anaconda3/lib/python3.12/site-packages/interpreter/computer_use/loop.py", line 186, in sampling_loop
    current_block.input = json.loads(current_block.partial_json)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Expected behavior

i was expecting it says something like "can't perform" or something, but not crash

### Screenshots

![image](https://github.com/user-attachments/assets/a88cd5ee-529d-4857-a346-c7897a293088)

### Open Interpreter version

0.4.3

### Python version

3.12.4

### Operating System name and version

macOS 14.7 (23H124)

**Comment by MikeBirdTech** [comment]
@artemu78 
Python 3.12 is not supported. Please try again with 3.11 or 3.10

**Comment by interpreterwork** [comment]
Thank you for reporting this and for helping build the classic Python version of Open Interpreter. This issue concerns the earlier Python/LiteLLM/Jupyter product; this repository now tracks the Rust Open Interpreter built on Codex. We are closing the legacy report here so current product tracking starts clean. If you still want to pursue it, the community-maintained classic fork is https://github.com/endolith/open-interpreter. If the same problem affects the current Interpreter release, please open a new issue with the current template and include the version, provider, model, wire API, harness, platform, and reproduction.
