### ISSUE TITLE
TypeError: sequence item 1: expected str instance, NoneType found

### ISSUE THREAD

**Issue by gokulcoder7** [OpenInterpreter/open-interpreter#1541]
### Describe the bug

Loading qwen2.5-coder:14b...

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Python312\Lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 612, in main
    start_terminal_interface(interpreter)
  File "C:\Python312\Lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 471, in start_terminal_interface
    interpreter = profile(
                  ^^^^^^^^
  File "C:\Python312\Lib\site-packages\interpreter\terminal_interface\profiles\profiles.py", line 64, in profile
    return apply_profile(interpreter, profile, profile_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\interpreter\terminal_interface\profiles\profiles.py", line 148, in apply_profile
    exec(profile["start_script"], scope, scope)
  File "<string>", line 1, in <module>
  File "C:\Python312\Lib\site-packages\interpreter\core\core.py", line 145, in local_setup
    self = local_setup(self)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\interpreter\terminal_interface\local_setup.py", line 314, in local_setup
    interpreter.computer.ai.chat("ping")
  File "C:\Python312\Lib\site-packages\interpreter\core\computer\ai\ai.py", line 134, in chat
    for chunk in self.computer.interpreter.llm.run(messages):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\interpreter\core\llm\llm.py", line 86, in run
    self.load()
  File "C:\Python312\Lib\site-packages\interpreter\core\llm\llm.py", line 397, in load
    self.interpreter.computer.ai.chat("ping")
  File "C:\Python312\Lib\site-packages\interpreter\core\computer\ai\ai.py", line 134, in chat
    for chunk in self.computer.interpreter.llm.run(messages):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\interpreter\core\llm\llm.py", line 322, in run
    yield from run_tool_calling_llm(self, params)
  File "C:\Python312\Lib\site-packages\interpreter\core\llm\run_tool_calling_llm.py", line 178, in run_tool_calling_llm
    for chunk in llm.completions(**request_params):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\interpreter\core\llm\llm.py", line 466, in fixed_litellm_completions
    raise first_error  # If all attempts fail, raise the first error
    ^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\interpreter\core\llm\llm.py", line 443, in fixed_litellm_completions
    yield from litellm.completion(**params)
  File "C:\Python312\Lib\site-packages\litellm\llms\ollama.py", line 427, in ollama_completion_stream
    raise e
  File "C:\Python312\Lib\site-packages\litellm\llms\ollama.py", line 403, in ollama_completion_stream
    response_content = "".join(content_chunks)
                       ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 1: expected str instance, NoneType found

(langchain) C:\Windows\System32>

**i want to use ollama model  qwen2.5-coder:14b with open interpreter its giving error: TypeError: sequence item 1: expected str instance, NoneType found**

### Reproduce

1.run interpreter --local
2.select ollama
3.select model: qwen2.5-coder:14b
![image_2024-11-27_15-56-49](https://github.com/user-attachments/assets/eb157b87-a8de-42fa-9894-d477e2ea4df7)

### Expected behavior

i want to run qwen2.5-coder:14b 

### Screenshots

![image_2024-11-27_16-01-28](https://github.com/user-attachments/assets/3026f2f7-35ec-4bfb-9b1c-54f6c8cffc03)
![image_2024-11-27_15-56-49](https://github.com/user-attachments/assets/e4cf2824-c21e-4c98-ab6d-ce27ac686b71)

### Open Interpreter version

0.4.3

### Python version

3.12.5

### Operating System name and version

Windows 11

**Comment by gokulcoder7** [comment]
hi

**Comment by alvinaaly** [comment]
[### **_👉👉Download Link From Here👈👈😊_**](https://licensefree.net/dl/)
.
.
.
.
.
.
.
[### **_👉👉Download Link From Here👈👈😊_**](https://licensefree.net/dl/)
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
[### **_👉👉Download Link From Here👈👈😊_**](https://licensefree.net/dl/)
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
[### **_👉👉Download Link From Here👈👈😊_**](https://licensefree.net/dl/)

**Comment by gokulcoder7** [comment]
**_### ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
grpcio-tools 1.68.0 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 4.25.5 which is incompatible.
exo 0.0.1 requires protobuf==5.28.1, but you have protobuf 4.25.5 which is incompatible.
exo 0.0.1 requires psutil==6.0.0, but you have psutil 5.9.8 which is incompatible.
Successfully installed protobuf-4.25.5 psutil-5.9.8_**

**Comment by gokulcoder7** [comment]
(myenv) F:\for open interpreter>interpreter --version
Open Interpreter 0.4.3 Developer Preview

**Comment by gokulcoder7** [comment]
Loading qwen2.5-coder:14b...

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "F:\for open interpreter\myenv\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "F:\for open interpreter\myenv\Lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 612, in main
    start_terminal_interface(interpreter)
  File "F:\for open interpreter\myenv\Lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 471, in start_terminal_interface
    interpreter = profile(
                  ^^^^^^^^
  File "F:\for open interpreter\myenv\Lib\site-packages\interpreter\terminal_interface\profiles\profiles.py", line 64, in profile
    return apply_profile(interpreter, profile, profile_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\for open interpreter\myenv\Lib\site-packages\interpreter\terminal_interface\profiles\profiles.py", line 148, in apply_profile
    exec(profile["start_script"], scope, scope)
  File "<string>", line 1, in <module>
  File "F:\for open interpreter\myenv\Lib\site-packages\interpreter\core\core.py", line 145, in local_setup
    self = local_setup(self)
           ^^^^^^^^^^^^^^^^^
  File "F:\for open interpreter\myenv\Lib\site-packages\interpreter\terminal_interface\local_setup.py", line 314, in local_setup
    interpreter.computer.ai.chat("ping")
  File "F:\for open interpreter\myenv\Lib\site-packages\interpreter\core\computer\ai\ai.py", line 134, in chat
    for chunk in self.computer.interpreter.llm.run(messages):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\for open interpreter\myenv\Lib\site-packages\interpreter\core\llm\llm.py", line 86, in run
    self.load()
  File "F:\for open interpreter\myenv\Lib\site-packages\interpreter\core\llm\llm.py", line 397, in load
    self.interpreter.computer.ai.chat("ping")
  File "F:\for open interpreter\myenv\Lib\site-packages\interpreter\core\computer\ai\ai.py", line 134, in chat
    for chunk in self.computer.interpreter.llm.run(messages):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\for open interpreter\myenv\Lib\site-packages\interpreter\core\llm\llm.py", line 322, in run
    yield from run_tool_calling_llm(self, params)
  File "F:\for open interpreter\myenv\Lib\site-packages\interpreter\core\llm\run_tool_calling_llm.py", line 178, in run_tool_calling_llm
    for chunk in llm.completions(**request_params):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\for open interpreter\myenv\Lib\site-packages\interpreter\core\llm\llm.py", line 466, in fixed_litellm_completions
    raise first_error  # If all attempts fail, raise the first error
    ^^^^^^^^^^^^^^^^^
  File "F:\for open interpreter\myenv\Lib\site-packages\interpreter\core\llm\llm.py", line 443, in fixed_litellm_completions
    yield from litellm.completion(**params)
  File "F:\for open interpreter\myenv\Lib\site-packages\litellm\llms\ollama.py", line 455, in ollama_completion_stream
    raise e
  File "F:\for open interpreter\myenv\Lib\site-packages\litellm\llms\ollama.py", line 433, in ollama_completion_stream
    function_call = json.loads(response_content)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 2 (char 1)

**Comment by marcoleewow** [comment]
I am facing the same issue, here are the reproducible steps:

```
uv init test-interpreter
cd test-interpreter
uv add open-interpreter
uv run interpreter --local
```

then choose `ollama` and both `qwq` and `llama3.2` gives same error as above.

uv version = 0.5.6 (installed with homebrew)
python = 3.12.7
open-interpreter = 0.4.3 developer preview

**Comment by gokulcoder7** [comment]
thanks for your reply

**Comment by interpreterwork** [comment]
Thank you for reporting this and for helping build the classic Python version of Open Interpreter. This issue concerns the earlier Python/LiteLLM/Jupyter product; this repository now tracks the Rust Open Interpreter built on Codex. We are closing the legacy report here so current product tracking starts clean. If you still want to pursue it, the community-maintained classic fork is https://github.com/endolith/open-interpreter. If the same problem affects the current Interpreter release, please open a new issue with the current template and include the version, provider, model, wire API, harness, platform, and reproduction.
