### ISSUE TITLE
the `DISPLAY` environment variable can be undefined

### ISSUE THREAD

**Issue by pminervini** [OpenInterpreter/open-interpreter#1552]
### Describe the bug

the code assumes it's always defined, but often it's not (e.g., if you're logging in via `ssh`)

### Reproduce

```
(base) pasquale@host:~$ interpreter

Open Interpreter 1.0.0
Copyright (C) 2024 Open Interpreter Team
Licensed under GNU AGPL v3.0

A modern command-line assistant.

Usage: i [prompt]
   or: interpreter [options]

Documentation: docs.openinterpreter.com
Run 'interpreter --help' for all options

> [sample instruction]
Traceback (most recent call last):
  File "/home/../miniconda3/lib/python3.12/site-packages/interpreter/tools/computer.py", line 14, in <module>
    import pyautogui
  File "/home/../miniconda3/lib/python3.12/site-packages/pyautogui/__init__.py", line 246, in <module>
    import mouseinfo
  File "/home/../miniconda3/lib/python3.12/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
                       ~~~~~~~~~~^^^^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'DISPLAY'
Failed to import pyautogui. Computer tool will not work.
```

### Expected behavior

no `KeyError: 'DISPLAY'`

### Open Interpreter version

latest @development

### Python version

3.12.7

### Operating System name and version

GNU/Linux aarch64

**Comment by pminervini** [comment]
nevermind it's an issue with pyautogui, it's easy to sort: https://stackoverflow.com/questions/52244164/importing-pyautogui-in-ubuntu-throwing-keyerror-display

**Comment by interpreterwork** [comment]
Thank you for reporting this and for helping build the classic Python version of Open Interpreter. This issue concerns the earlier Python/LiteLLM/Jupyter product; this repository now tracks the Rust Open Interpreter built on Codex. We are closing the legacy report here so current product tracking starts clean. If you still want to pursue it, the community-maintained classic fork is https://github.com/endolith/open-interpreter. If the same problem affects the current Interpreter release, please open a new issue with the current template and include the version, provider, model, wire API, harness, platform, and reproduction.
